version: 2
deployment:
  commands:
    - echo "Starting the deployment process..."
    - echo "Copying files to public_html directory..."
    - cp -r * /home/bizzaehz/public_html/bizzviz/
    - echo "Deployment completed successfully."
